.cache: &cache
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - .tox

before_script:
    - "[ -s $HOME/.prep_gitlab_runner.sh ] && . $HOME/.prep_gitlab_runner.sh"
tox:
  <<: *cache
  tags:
    - shell
  stage: test
  allow_failure: true
  script:
    - tox

flake2:
  tags:
    - shell
  stage: test
  allow_failure: true
  script:
    - virtualenv -p $(pyenv which python2.7) venv2
    - source venv2/bin/activate ; python pip install -r requirements.txt flake8
    - source venv2/bin/activate ; python flake8
    
flake3:
  tags:
    - shell
  stage: test
  allow_failure: true
  script:
    - virtualenv -p $(pyenv which python3.5) venv3
    - source venv3/bin/activate ; python pip install -r requirements.txt flake8
    - source venv3/bin/activate ; python flake8
    
