.cache: &cache
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - .tox

before_script:
    - "[ -s '$HOME/.prep_gitlab_runner.sh' ] && . $HOME/.prep_gitlab_runner.sh"
tox:
  <<: *cache
  tags:
    - shell
  stage: test
  allow_failure: true
  script:
    - tox
