.cache: &cache
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - .tox

before_script:
    - echo "HOME is $HOME"
    - "[ -f $HOME/.prep_gitlab_runner.sh ] && . $HOME/.prep_gitlab_runner.sh"
tox:
  <<: *cache
  tags:
    - shell
  stage: test
  allow_failure: true
  script:
    - virtualenv -p $(pyenv which python2.7) venv2
    - source venv2/bin/activate ; python -m pip install tox
    - tox

flake2:
  tags:
    - shell
  stage: test
  allow_failure: true
  script:
    - virtualenv -p $(pyenv which python2.7) venv2
    - source venv2/bin/activate ; python -m pip install -r requirements/all_py2.txt flake8
    - source venv2/bin/activate ; python -m flake8 mytb
    
flake3:
  tags:
    - shell
  stage: test
  allow_failure: true
  script:
    - virtualenv -p $(pyenv which python3.5) venv3
    - source venv3/bin/activate ; python -m pip install -r requirements/all.txt flake8
    - source venv3/bin/activate ; python -m flake8 mytb
    
