[tool.isort]
profile = "black"
force_single_line = true
line_length = 80
skip_gitignore = true
ignore_comments = true
honor_noqa = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "MYTB", "LOCALFOLDER"]
known_mytb = ["mytb"]

[tool.black]
line-length = 80
